S -> Programa
Programa -> ListaContexto PROCEDURE ID IS ListaDeclaracoes BEGIN ListaComandos END ID PONTO_VIRGULA
ListaContexto -> ListaContexto Contexto
ListaContexto -> 
Contexto -> WITH Acesso PONTO_VIRGULA
Contexto -> USE Acesso PONTO_VIRGULA
ListaDeclaracoes -> ListaDeclaracoes Declaracao
ListaDeclaracoes -> 
ListaComandos -> ListaComandos Comando
ListaComandos -> 
Declaracao -> DeclTipo
DeclTipo -> TYPE ID IS DefTipo PONTO_VIRGULA
DefTipo -> DefRecord
DefTipo -> DefArray
DefRecord -> RECORD ListaCampos END RECORD
ListaCampos -> ListaCampos Campo
ListaCampos -> 
Campo -> ListaIds DOIS_PONTOS Acesso PONTO_VIRGULA
ListaIds -> ListaIds VIRGULA ID
ListaIds -> ID
DefArray -> ARRAY ABRE_PARENTESES DefinicaoIndice FECHA_PARENTESES OF Acesso
DefinicaoIndice -> Acesso RANGE MENOR_MAIOR
DefinicaoIndice -> Expressao PONTO_PONTO Expressao
Declaracao -> DeclVar
DeclVar -> ListaIds DOIS_PONTOS TipoVar PONTO_VIRGULA
DeclVar -> ListaIds DOIS_PONTOS TipoVar ATRIBUICAO Expressao PONTO_VIRGULA
TipoVar -> Acesso
TipoVar -> ARRAY ABRE_PARENTESES Expressao PONTO_PONTO Expressao FECHA_PARENTESES OF Acesso
TipoVar -> Acesso ABRE_PARENTESES Expressao PONTO_PONTO Expressao FECHA_PARENTESES
Declaracao -> DeclFunc
DeclFunc -> FUNCTION ID ParametrosFunc RETURN Acesso IS ListaDeclaracoes BEGIN ListaComandos END ID PONTO_VIRGULA
ParametrosFunc -> ABRE_PARENTESES ListaParams FECHA_PARENTESES
ParametrosFunc -> 
ListaParams -> ListaParams PONTO_VIRGULA Parametro
ListaParams -> Parametro
Parametro -> ListaIds DOIS_PONTOS Modificador Acesso
Modificador -> IN OUT
Modificador -> 
Comando -> ComandoIf
Comando -> ComandoWhile
Comando -> ComandoFor
Comando -> ComandoReturn
Comando -> ComandoAtribuicao
Comando -> ComandoChamada
Comando -> ComandoExit
Comando -> NULL PONTO_VIRGULA
ComandoIf -> IF Expressao THEN ListaComandos FimIf
FimIf -> END IF PONTO_VIRGULA
FimIf -> ELSIF Expressao THEN ListaComandos FimIf
FimIf -> ELSE ListaComandos END IF PONTO_VIRGULA
ComandoWhile -> WHILE Expressao LOOP ListaComandos END LOOP PONTO_VIRGULA
ComandoFor -> FOR ID IN ReversePart Expressao PONTO_PONTO Expressao LOOP ListaComandos END LOOP PONTO_VIRGULA
ReversePart -> REVERSE
ReversePart -> 
ComandoExit -> EXIT WHEN Expressao PONTO_VIRGULA
ComandoExit -> EXIT PONTO_VIRGULA
ComandoReturn -> RETURN Expressao PONTO_VIRGULA
ComandoReturn -> RETURN PONTO_VIRGULA
ComandoAtribuicao -> Acesso ATRIBUICAO Expressao PONTO_VIRGULA
ComandoChamada -> Acesso PONTO_VIRGULA
Acesso -> ID
Acesso -> Acesso PONTO ID
Acesso -> Acesso ABRE_PARENTESES ListaExp FECHA_PARENTESES
Acesso -> Acesso ASPAS_SIMPLES ID
ListaExp -> ListaExpNotEmpty
ListaExp -> 
ListaExpNotEmpty -> ListaExpNotEmpty VIRGULA Expressao
ListaExpNotEmpty -> Expressao
Expressao -> ExpLogica
ExpLogica -> ExpLogica OR ExpRelacional
ExpLogica -> ExpLogica AND ExpRelacional
ExpLogica -> ExpLogica OR ELSE ExpRelacional
ExpLogica -> ExpLogica AND THEN ExpRelacional
ExpLogica -> ExpRelacional
ExpRelacional -> ExpRelacional IGUAL ExpAditiva
ExpRelacional -> ExpRelacional DIFERENTE ExpAditiva
ExpRelacional -> ExpRelacional MENOR ExpAditiva
ExpRelacional -> ExpRelacional MENOR_IGUAL ExpAditiva
ExpRelacional -> ExpRelacional MAIOR ExpAditiva
ExpRelacional -> ExpRelacional MAIOR_IGUAL ExpAditiva
ExpRelacional -> ExpAditiva
ExpAditiva -> ExpAditiva MAIS ExpMultiplicativa
ExpAditiva -> ExpAditiva MENOS ExpMultiplicativa
ExpAditiva -> ExpMultiplicativa
ExpMultiplicativa -> ExpMultiplicativa MULTIPLICACAO ExpUnaria
ExpMultiplicativa -> ExpMultiplicativa DIVISAO ExpUnaria
ExpMultiplicativa -> ExpMultiplicativa MOD ExpUnaria
ExpMultiplicativa -> ExpUnaria
ExpUnaria -> MENOS Fator
ExpUnaria -> NOT Fator
ExpUnaria -> Fator
Fator -> ABRE_PARENTESES Expressao FECHA_PARENTESES
Fator -> NUM_INT
Fator -> NUM_DEC
Fator -> STRING
Fator -> Acesso